# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  media_hash: j432l5li2ul5kl4h52k4hk5h45h42k5h4k25h42k5hkjf9ds
  secret_key_base:
  aws_access_key_id:
  aws_secret_access_key:
  output_quality: "128abr"
  output_format: "mp3"
  aws_region: "eu-west-1"
  s3_bucket:
  s3_host_name: 's3-eu-west-1.amazonaws.com'
  api_version: "v1"
  jingle_modulo: 3
  youtube_api_key:
  youtube_channel_id: UCcqe1EHmdaLVBwfqk5OtmXw
  track_new_limit: 4
  track_auto_featured_limit: 6

development:
  <<: *default
  domain_api_url: "http://api.lereglement.here:3000"
  domain_url: "http://lereglement.here:3000"
  path_static: "./static"

test:
  <<: *default
  domain_api_url: "http://api.lereglement.here:3000"
  domain_url: "http://lereglement.here:3000"
  path_static: "./static"

staging:
  <<: *default
  domain_api_url: "http://api-staging.lereglement.xyz"
  domain_url: "http://staging.lereglement.sale"
  path_static: "./static"

production:
  <<: *default
  domain_api_url: "http://api.lereglement.xyz"
  domain_url: "http://lereglement.sale"
  path_static: "./static"
