# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  media_hash:
  secret_key_base:
  aws_access_key_id:
  aws_secret_access_key:
  instagram_client_id:
  instagram_client_secret:
  batch_api_key:
  batch_ios:
  batch_android:
  jwt_delay: 200
  jwt_issuer: 'bonnie'
  jwt_audience: 'client'
  aws_region: "eu-central-1"
  aws_host: "cellar.services.clever-cloud.com"

development:
  <<: *default
  domain_image_url: "http://api.getbonnie.here:3000/v3/media"
  domain_api_url: "http://api.getbonnie.here:3000"
  domain_url: "http://getbonnie.here:3000"
  path_static: "./static"
  s3_bucket: "bonnie-dev"

test:
  <<: *default
  domain_image_url: "http://api.getbonnie.here:3000/v3/media"
  domain_api_url: "http://api.getbonnie.here:3000"
  domain_url: "http://getbonnie.here:3000"
  path_static: "./static"

staging:
  <<: *default
  domain_image_url: "https://api-dev.getbonnie.com/v3/media"
  domain_api_url: "https://api-dev.getbonnie.com"
  domain_url: "https://dev.getbonnie.com"
  path_static: "./static"
  s3_bucket: "bonnie-staging"

production:
  <<: *default
  domain_image_url: "https://getbonnie.com/v3/media"
  domain_api_url: "https://api.getbonnie.com"
  domain_url: "https://getbonnie.com"
  path_static: "./static"
  s3_bucket: "bonnie-prod"
