# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  media_hash: j432l5li2ul5kl4h52k4hk5h45h42k5h4k25h42k5hkjf9ds
  secret_key_base:
  aws_access_key_id:
  aws_secret_access_key:
  output_quality: "128abr"
  output_format: "mp3"
  aws_region: "eu-west-1"
  aws_host: "cellar.services.clever-cloud.com"
  aws_host: "cellar.services.clever-cloud.com"

development:
  <<: *default
  domain_image_url: "http://api.lereglement.here:3000/v1/media"
  domain_api_url: "http://api.lereglement.here:3000"
  domain_url: "http://lereglement.here:3000"
  path_static: "./static"
  s3_bucket: "le-reglement-v2"

test:
  <<: *default
  domain_image_url: "http://api.lereglement.here:3000/v1/media"
  domain_api_url: "http://api.lereglement.here:3000"
  domain_url: "http://lereglement.here:3000"
  path_static: "./static"

staging:
  <<: *default
  domain_image_url: "https://api-dev.lereglement.sale/v1/media"
  domain_api_url: "https://api-dev.lereglement.sale"
  domain_url: "https://dev.lereglement.sale"
  path_static: "./static"
  s3_bucket: "lereglement-staging"

production:
  <<: *default
  domain_image_url: "https://lereglement.sale/v1/media"
  domain_api_url: "https://api.lereglement.sale"
  domain_url: "https://lereglement.sale"
  path_static: "./static"
  s3_bucket: "lereglement-prod"
