:concurrency: 5
:pidfile: tmp/pids/sidekiq.pid
development:
  :pidfile: /tmp/sidekiq.pid
  :concurrency: 10
staging:
  :pidfile: /tmp/sidekiq.pid
  :concurrency: 10
production:
  :pidfile: /tmp/sidekiq.pid
  :concurrency: 20
:queues:
  - default
  - [myqueue, 2]
